# Generated by Django 4.1.3 on 2023-06-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flutterapp.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flutterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=64)),
                ('house_number', models.CharField(max_length=64)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+92', max_length=128, region='PK')),
                ('postal_code', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='image',
            field=models.ImageField(upload_to=flutterapp.models.get_image_path, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
