# Generated by Django 4.2.1 on 2023-06-11 04:12

from django.db import migrations, models
import geoposition.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flutterapp', '0002_addressinfo_alter_cylinder_image_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address', geoposition.fields.GeopositionField(max_length=42)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+92', max_length=128, region='PK')),
            ],
        ),
    ]
