# Generated by Django 4.2.1 on 2023-06-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutterapp', '0003_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='address',
            new_name='location',
        ),
    ]
