# Generated by Django 4.2.1 on 2023-06-11 07:53

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('flutterapp', '0004_rename_address_distributor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
