# Generated by Django 4.2.1 on 2023-06-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flutterapp', '0005_alter_distributor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flutterapp.distributor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Alfa', 'Alfa'), ('Cash On Delivery', 'Cash On Delivery')], max_length=64),
        ),
    ]
