# Generated by Django 4.2.1 on 2023-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutterapp', '0006_orderinfo_distributor_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('COD', 'COD')], max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
